export const data = [
  {
    id: 1,
    first_name: "Aarav",
    last_name: "Sharma",
    email: "aarav.sharma@example.com",
    phone: "+91-9876543210",
    address: "12 MG Road, Bengaluru, Karnataka",
  },
  {
    id: 2,
    first_name: "Ishita",
    last_name: "Verma",
    email: "ishita.verma@example.com",
    phone: "+91-8765432109",
    address: "45 Civil Lines, Lucknow, Uttar Pradesh",
  },
  {
    id: 3,
    first_name: "Rohan",
    last_name: "Kapoor",
    email: "rohan.kapoor@example.com",
    phone: "+91-7654321098",
    address: "88 Park Street, Kolkata, West Bengal",
  },
  {
    id: 4,
    first_name: "Sneha",
    last_name: "Patel",
    email: "sneha.patel@example.com",
    phone: "+91-6543210987",
    address: "21 SG Highway, Ahmedabad, Gujarat",
  },
  {
    id: 5,
    first_name: "Aditya",
    last_name: "Singh",
    email: "aditya.singh@example.com",
    phone: "+91-9123456780",
    address: "14 Sector 18, Noida, Uttar Pradesh",
  },
  {
    id: 6,
    first_name: "Priya",
    last_name: "Menon",
    email: "priya.menon@example.com",
    phone: "+91-9234567810",
    address: "33 MG Road, Kochi, Kerala",
  },
  {
    id: 7,
    first_name: "Kabir",
    last_name: "Chopra",
    email: "kabir.chopra@example.com",
    phone: "+91-9345678920",
    address: "67 Pali Hill, Mumbai, Maharashtra",
  },
  {
    id: 8,
    first_name: "Ananya",
    last_name: "Reddy",
    email: "ananya.reddy@example.com",
    phone: "+91-9456789030",
    address: "56 Jubilee Hills, Hyderabad, Telangana",
  },
  {
    id: 9,
    first_name: "Vikram",
    last_name: "Bose",
    email: "vikram.bose@example.com",
    phone: "+91-9567890140",
    address: "22 Salt Lake, Kolkata, West Bengal",
  },
  {
    id: 10,
    first_name: "Lucky",
    last_name: "Singh",
    email: "luckysingh@gmail.com",
    phone: "1234567890",
    address: "not yet decided",
  },
  {
    id: 11,
    first_name: "Lucky",
    last_name: "Singh",
    email: "luckysingh@gmail.com",
    phone: "1234567890",
    address: "not yet decided",
  },
];
